
name: Deploy to Amazon LightSail

on:
  push:
    branches: [ "production" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: teste

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy code
        run: |
          echo "Executando o deploy..."
          echo "Token de deploy:  ${{ secrets.TARGET_HOST }}"
          echo "Token de TESTE: ${{ secrets.TARGET_HOST }}"
          echo  ${{ secrets.TARGET_HOST }}
          echo  ${{ secrets.AWS_REGION }}
          echo  ${{ secrets.OUTRO_SEGREDO }}

      # - name: "Copiar arquivos para VPS"
      #   uses: appleboy/scp-action@v0.1.7
      #   with:
      #     host: ${{ secrets.TARGET_HOST }}
      #     username:  ${{ secrets.TARGET_USER }}
      #     key: ${{ secrets.PRIVATE_KEY }}
      #     source: "./"
      #     target: "teste/sistema"



