
name: Deploy to Amazon LightSail

on:
  push:
    branches: [ "production" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Copiar arquivos para VPS"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.TARGET_HOST }}
          username:  ${{ secrets.TARGET_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "./"
          target: "teste/sistema"



